In [211]:
import numpy as np
import typing as tp

def find_dist_matr(A: np.ndarray, B:np.ndarray) -> np.ndarray:
    A1 = np.expand_dims(A.transpose(), axis = 0)
    B1 = np.expand_dims(B, axis = 2)
    D = ((A1 - B1)*(A1 - B1)).sum(axis = 1)
    return D

def find_nearest_points(A: np.ndarray, B: np.ndarray, k: int) -> np.ndarray:
    m = B.shape[0]
    Dists = find_dist_matr(A, B)
    Idxs = np.argsort(Dists)
    Sorted_Idxs = np.sort(Idxs)
    adv_idxs = np.arange(Idxs.shape[0])[:,None], Idxs.argsort(axis = 1)
    return Sorted_Idxs[adv_idxs][:,:k] + 1

In [212]:
def my_find_nearest_points(A: np.ndarray, B: np.ndarray, k: int) -> np.ndarray:
    dists = list()
    lowests = list()
    for i in range(len(B)):
        lowests.append(list())
        dists.clear()
        for j in range(len(A)):
            dists.append(((B[i] - A[j])*(B[i] - A[j])).sum())
        D = dists.copy()
        dists.sort()
        for j in range(len(A)):
            if D[j] <= dists[k - 1]:
                lowests[i].append(j + 1)
    return np.array(lowests)

In [213]:
np.random.seed(31)

A = np.random.uniform(0, 10, size=(5, 2))
B = np.random.uniform(0, 10, size=(5, 2))
pans = find_nearest_points(A, B, 3)
#jans = my_find_nearest_points(A, B, 3)
print(pans)
#print(jans)
#np.all(pans == jans)

[[3.70117488e+01 8.29034931e+01 7.43638762e+00 7.69160596e+01
  2.61644382e+00]
 [4.26085180e+01 3.21383953e+01 2.97374752e+01 1.87492694e+01
  3.64998630e+01]
 [6.42031554e+01 1.15578337e+02 3.02558417e+00 7.63004892e+01
  1.22959134e+01]
 [8.27772258e+01 9.59075990e+01 6.24063948e+00 2.13216899e+01
  3.69207443e+01]
 [3.42075743e-02 2.25358070e+01 6.58779923e+01 1.13869627e+02
  2.09465177e+01]]

[[4 2 0 3 1]
 [3 2 1 4 0]
 [2 4 0 3 1]
 [2 3 4 0 1]
 [0 4 1 2 3]]

[4 2 0 3 1]
(array([1, 2, 4]),)

[[3 5 2]
 [5 3 2]
 [3 5 1]
 [4 5 1]
 [1 3 4]]


In [52]:
A = np.array([
  [0, 0],
  [1, 0],
  [2, 0]
])

B = np.array([
  [0, 1],
  [2, 1]
])
find_nearest_points(A, B, 2) 

Dists: 
[[1 2 5]
 [5 2 1]]

[1 2 5]
ArgSort: 
[[0 1 2]
 [2 1 0]]

[[0 1 2]
 [0 1 2]]


array([[1, 2],
       [3, 2]])

In [216]:
m = B.shape[0]
Dists = find_dist_matr(A, B)
print(Dists)
Idxs = np.argsort(Dists)
Idxs

[[3.70117488e+01 8.29034931e+01 7.43638762e+00 7.69160596e+01
  2.61644382e+00]
 [4.26085180e+01 3.21383953e+01 2.97374752e+01 1.87492694e+01
  3.64998630e+01]
 [6.42031554e+01 1.15578337e+02 3.02558417e+00 7.63004892e+01
  1.22959134e+01]
 [8.27772258e+01 9.59075990e+01 6.24063948e+00 2.13216899e+01
  3.69207443e+01]
 [3.42075743e-02 2.25358070e+01 6.58779923e+01 1.13869627e+02
  2.09465177e+01]]


array([[4, 2, 0, 3, 1],
       [3, 2, 1, 4, 0],
       [2, 4, 0, 3, 1],
       [2, 3, 4, 0, 1],
       [0, 4, 1, 2, 3]])