In [169]:
import numpy as np
import typing as tp

def find_max_sum_segment(array: tp.List[int], k: int) -> int:
    array = np.array(array)
    n = array.size
    Ones = np.ones(n)
    UpperTriangle = np.triu(Ones, -k + 1)
    LowerTriangle = np.tril(Ones, 0)
    ChooseMatr = np.logical_and(UpperTriangle, LowerTriangle)
    ChooseMatr = ChooseMatr[0:n, 0:n-k+1]
    Sums = (((ChooseMatr.transpose())*(array.transpose())).sum(axis = 1))
    return Sums.max()

In [167]:
find_max_sum_segment(np.array([1, 2, 3, 4]), 2)

[3 5 7]


7

In [168]:
import random
random.seed(31)
array = random.choices(range(10), k=10)
print(array)
print(find_max_sum_segment(array, 10))

[0, 1, 3, 6, 1, 1, 2, 7, 1, 7]
[29]
29


In [92]:
k = 4
n = 10
A = np.ones(n)
TU = np.triu(A, -k+1)
TL = np.tril(A, 0) 
Q = np.logical_and(TU, TL)
print(Q)

[[ True False False False False False False False False False]
 [ True  True False False False False False False False False]
 [ True  True  True False False False False False False False]
 [ True  True  True  True False False False False False False]
 [False  True  True  True  True False False False False False]
 [False False  True  True  True  True False False False False]
 [False False False  True  True  True  True False False False]
 [False False False False  True  True  True  True False False]
 [False False False False False  True  True  True  True False]
 [False False False False False False  True  True  True  True]]


In [97]:
find_max_sum_segment(np.array([1, 2, 3, 4, 5]), 3)

5

In [178]:
np.random.seed(31)

A = np.random.uniform(0, 10, size=(5, 2))
B = np.random.uniform(0, 10, size=(5, 2))
print(A)
print()
print(B)
((A - B[0])*(A - B[0])).sum(axis = 1)

[[2.86053822 9.58105567]
 [7.70312932 9.86870003]
 [2.08165462 1.36917049]
 [9.08373802 0.68638518]
 [0.75332722 5.43534689]]

[[0.89399717 3.82393268]
 [6.6856044  4.29169023]
 [0.43956307 1.94285989]
 [4.46659484 0.62573278]
 [2.97567282 9.436309  ]]


array([37.01174883, 82.90349312,  7.43638762, 76.9160596 ,  2.61644382])

In [186]:
np.random.seed(31)
A = np.random.uniform(0, 10, size=(5, 2))
B = np.random.uniform(0, 10, size=(5, 2))
print(A)

[[2.86053822 9.58105567]
 [7.70312932 9.86870003]
 [2.08165462 1.36917049]
 [9.08373802 0.68638518]
 [0.75332722 5.43534689]]
